---
- name: This is a hello-world example
  hosts: alias
  remote_user: shivi
  become: sudo
  vars:
        http_port: 80
        max_clients: 200 
  tasks:
  - action: ping
  - name: copy application code to document root
    template: src=/home/shivi/front.html dest=/home/shivi/var/www/html/index.html
    notify: restart apache2
    


 
       
